# Generated by Django 4.2.6 on 2023-10-18 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='распорядок')),
                ('period', models.DurationField(verbose_name='раз в какое количество часов')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='время начала')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='время окончания')),
                ('last_event', models.TimeField(blank=True, null=True, verbose_name='время последнего выполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='расписание')),
                ('mon', models.TimeField(verbose_name='время для привычки в пн')),
                ('tue', models.TimeField(verbose_name='время для привычки в вт')),
                ('wed', models.TimeField(verbose_name='время для привычки в ср')),
                ('th', models.TimeField(verbose_name='время для привычки в чт')),
                ('fri', models.TimeField(verbose_name='время для привычки в пт')),
                ('sat', models.TimeField(verbose_name='время для привычки в сб')),
                ('sun', models.TimeField(verbose_name='время для привычки в вс')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, unique=True, verbose_name='действие')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место для привычки')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='награда')),
                ('is_it_rewarding_habit', models.BooleanField(verbose_name='это привычка поощрения')),
                ('time_to_done', models.DurationField(verbose_name='время на выполнение привычки')),
                ('is_public', models.BooleanField(verbose_name='видна другим пользователям')),
                ('on_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.schedule', verbose_name='расписание для привычки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('periodic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.period', verbose_name='периодичность привычки')),
                ('rewarding_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка поощрения')),
            ],
        ),
    ]
