# Generated by Django 4.2.6 on 2023-10-20 00:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_period_owner_schedule_owner_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_done',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(seconds=120))], verbose_name='время на выполнение привычки'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(days=1))], verbose_name='раз в какое количество часов'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fri',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в пт'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в пн'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в сб'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в вс'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='th',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в чт'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в вт'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed',
            field=models.TimeField(blank=True, null=True, verbose_name='время для привычки в ср'),
        ),
    ]
